<?php

return [
    'en' => [
        'isRequired' => 'The field "%s" is required',
        'isInt' => 'The field "%s" must be an integer number',
        'isNumeric' => 'The field "%s" must be a number',
        'isDecimal' => 'The field "%s" must be a number',
        'isSafeText' => 'The field "%s" contains not allowed characters',
        'isDateTime' => 'The field "%s" must be a valid date time',
        'isDate' => 'The field "%s" must be a valid date',
        'isTime' => 'The field "%s" must be a valid time',
        'isBool' => 'The field "%s" must be a yes/no value',
        'isEmail' => 'The field "%s" must be a valid email',
        'isArray' => 'The field "%s" must be an array',
        'isJson' => 'The field "%s" must be a valid JSON',
        'regex' => 'The field "%s" does not match the required format',
        'minLength' => 'The field "%s" must have at least %s characters',
        'maxLength' => 'The field "%s" must have at most %s characters',
        'mbMinLength' => 'The field "%s" must have at least %s characters',
        'mbMaxLength' => 'The field "%s" must have at most %s characters',
        'min' => 'The field "%s" must be greater or equal to %s',
        'max' => 'The field "%s" must be less or equal to %s',
        'greater' => 'The field "%s" must be greater than "%s"',
        'greaterDatetime' => 'The field "%s" must be greater than "%s"',
        'greaterDate' => 'The field "%s" must be greater than "%s"',
        'less' => 'The field "%s" must be less than "%s"',
        'lessDatetime' => 'The field "%s" must be less than "%s"',
        'lessDate' => 'The field "%s" must be less than "%s"',
        'equal' => 'The field "%s" must be equal to "%s"',
        'notEqual' => 'The field "%s" must be different from "%s"',
        'excatly' => 'The field "%s" must be exactly "%s"',
        'notExactly' => 'The field "%s" must be different from "%s"',
    ],
    'es' => [
        'isRequired' => 'El campo "%s" es requerido',
        'isInt' => 'El campo "%s" debe ser un número entero',
        'isNumeric' => 'El campo "%s" debe ser un número',
        'isDecimal' => 'El campo "%s" debe ser un número',
        'isSafeText' => 'El campo "%s" contiene caracteres no permitidos',
        'isDateTime' => 'El campo "%s" debe ser una fecha y hora válida',
        'isDate' => 'El campo "%s" debe ser una fecha válida',
        'isTime' => 'El campo "%s" debe ser una hora válida',
        'isBool' => 'El campo "%s" debe ser un valor de sí/no',
        'isEmail' => 'El campo "%s" debe ser un correo válido',
        'isArray' => 'El campo "%s" debe ser un arreglo',
        'isJson' => 'El campo "%s" debe ser un JSON válido',
        'regex' => 'El campo "%s" no coincide con el formato requerido',
        'minLength' => 'El campo "%s" debe tener al menos %s caracteres',
        'maxLength' => 'El campo "%s" debe tener como máximo %s caracteres',
        'mbMinLength' => 'El campo "%s" debe tener al menos %s caracteres',
        'mbMaxLength' => 'El campo "%s" debe tener como máximo %s caracteres',
        'min' => 'El campo "%s" debe ser mayor o igual a %s',
        'max' => 'El campo "%s" debe ser menor o igual a %s',
        'greater' => 'El campo "%s" debe ser mayor que "%s"',
        'greaterDatetime' => 'El campo "%s" debe ser mayor que "%s"',
        'greaterDate' => 'El campo "%s" debe ser mayor que "%s"',
        'less' => 'El campo "%s" debe ser menor que "%s"',
        'lessDatetime' => 'El campo "%s" debe ser menor que "%s"',
        'lessDate' => 'El campo "%s" debe ser menor que "%s"',
        'equal' => 'El campo "%s" debe ser igual a "%s"',
        'notEqual' => 'El campo "%s" debe ser diferente de "%s"',
        'excatly' => 'El campo "%s" debe ser exactamente "%s"',
        'notExactly' => 'El campo "%s" debe ser diferente de "%s"',
    ],
];